version: '3.9'
services:
  web:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - ${APP_PORT}:3001
    networks:
      - default
    volumes:
      - data:/data

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
